### ISSUE TITLE
Add a new retrieve method 'findByModelId'

### ISSUE THREAD

**Issue by inh3** [marionettejs/backbone.babysitter#21]
I have a desire to find a view by its underlying model's [id](http://backbonejs.org/#Model-id).  Backbone allows you specify the value of this with the [idAttribute](http://backbonejs.org/#Model-idAttribute) in order to store a unique key relevant to a back-end service.

I realize I could achieve this by essentially doing:

``` javascript
container.add(aView, "id");
```

However, using Marionette's CompositeView or CollectionView, the container's add is called within an function that isn't easily overridden (and don't really want to).

``` javascript
addItemView: function(item, ItemView, index){
  var itemViewOptions = Marionette.getOption(this, "itemViewOptions");
  if (_.isFunction(itemViewOptions)){
    itemViewOptions = itemViewOptions.call(this, item, index);
  }

  var view = this.buildItemView(item, ItemView, itemViewOptions);

  this.addChildViewEventForwarding(view);

  this.triggerMethod("before:item:added", view);

  this.children.add(view);

  this.renderItemView(view, index);

  if (this._isShown){
     Marionette.triggerMethod.call(view, "show"):
  }

  this.triggerMethod("after:item:added", view);
},
```

Since, the 'id' attribute of the model is defined by Backbone, I think it would worthwhile to add the capability to find the view by the attribute if defined.

I think this could easily be achieved by simply adding a new index object.

``` javascript
this._indexByModelId = {};

add: function(view, customIndex){

  ...

  // index it by model
  if (view.model){

    ...

    // add index by model id if present
    if(view.model.id) {
      this._indexByModelId[view.model.id] = viewCid;
    }
  }

  ...

}

...

findByModelId: function(modelId){
  var viewCid = this._indexByModelId[modelId];
  return this.findByCid(viewCid);
},

...
```

**Comment by absolux** [comment]
Hi @inh3, you can use custom index instead. no?
