### ISSUE TITLE
No reuse of child-view closing

### ISSUE THREAD

**Issue by rjharmon** [marionettejs/backbone.babysitter#38]
It seems to me that the backbone babysitter should listen for close events on the parent view, enabling any user of the babysitter to take advantage of complete sub-view lifecycle.  It's great to have that lifecycle management in CollectionView and CompositeView, and it would be even better to be able to harness it for other cases.

Would you accept a patch that refactors the ChildViewContainer and the CollectionView to move the child-view closing responsibility to the ChildViewContainer, perhaps by passing it an optional parent view in the second arg to the constructor?  Or will it be necessary to have a separate entity responsible for child-view closing (e.g. due to memory-management issues)?

**Comment by paulfalgout** [comment]
I'm not sure I follow exactly, but this is as very old issue.  For now I'm just cleaning up this repo
