### ISSUE TITLE
`reduce` method is not delegated

### ISSUE THREAD

**Issue by romanbsd** [marionettejs/backbone.babysitter#53]
Please delegate the `reduce` method to the child views.

**Comment by samccone** [comment]
@romanbsd would you mind expanding on this issue? I am not sure I follow

**Comment by romanbsd** [comment]
There're a few underscore methods which can be invoked on the child views, set here:
https://github.com/marionettejs/backbone.babysitter/blob/master/src/childviewcontainer.js#L135
I ask for adding `reduce` to this list.

**Comment by samccone** [comment]
ah thank you for clarifying, yeah I see no problem adding reduce in here, would you like to open a PR?

**Comment by romanbsd** [comment]
https://github.com/marionettejs/backbone.babysitter/pull/54

**Comment by paulfalgout** [comment]
Ping @samccone  This issue can be closed

**Comment by samccone** [comment]
Good catch
