### ISSUE TITLE
Remove `call` and `apply`

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.babysitter#57]
In favor of just `invoke`. Thoughts @marionettejs/marionette-core ? 

Related: https://github.com/marionettejs/backbone.babysitter/issues/56

**Comment by jasonLaster** [comment]
code:
https://github.com/marionettejs/backbone.babysitter/blob/master/lib/backbone.babysitter.js#L137-L150

we should kill this and be consistent w/ underscore and not break JS norms.

we're still pre-1.0 so there isn't an issue w/ semvar.

**Comment by jmeas** [comment]
My only hesitation to remove it is that nearly all of Babysitter could be deleted / replaced with something better in the next version of Marionette, sort of like Wreqr => Radio.

Do we want to make breaking changes to this legacy stuff, which could cause lots of folks to refactor their apps, or should we just build something better and sunset this thing?

**Comment by jasonLaster** [comment]
:8ball:

**Comment by ahumphreys87** [comment]
Im in favour of adding an enumerable class in Marionette v3 as in https://github.com/marionettejs/backbone.marionette/issues/2312

I actually started on this here: https://github.com/ahumphreys87/backbone.enumerable I haven't got too far though :laughing: 

id like to get your thoughts on what we could do with that though? Do we just wanna proxy underscore methods similar to what `Backbone.Collection` does?

**Comment by jasonLaster** [comment]
@ahumphreys87 i like what you're saying.

I added this last year, Sam said nobody would want it. He was wrong, you do
https://github.com/marionettejs/backbone.marionette/blob/master/src/helpers.js#L114-L131

I think the better approach is to do what ruby does and let you mixin it in if you add an `each` function

**Comment by paulfalgout** [comment]
So babysitter should be made 1.0.0 for the sake of making marionette safe, but there's no reason if we don't replace it for v3 (which certainly there's enough on the plate as it is) we could just bump it to 1.0.0 with the breaking change for the v3 release

**Comment by ahumphreys87** [comment]
Yeah Ember.Enumerable is mentioned in the issue above: http://emberjs.com/api/classes/Ember.Enumerable.html

Does this mean we need to create a mixin strategy for marionette? Or do we have this without me realising as well?

@paulfalgout i think the only place we use babysitter is collectionView currently and that will already go under quite a bit of work. I dont think removing babysitter will be _that_ much overhead for it. The concerns we had previously we for people using the `findBy*` functions on `collectionView.children` in V3 we can change this and say - if you wanna do this, use the functions from our enumerable object

**Comment by jasonLaster** [comment]
lets, move this discussion to a separate issue. it's good but different
