### ISSUE TITLE
Can we get a new tag for Backbone#1.2.0 support?

### ISSUE THREAD

**Issue by SomethingSexy** [marionettejs/backbone.babysitter#59]

**Comment by samccone** [comment]
Hi @SomethingSexy babysitter is currently not tested against 1.2 once it is and things are still passing we can do this!

**Comment by SomethingSexy** [comment]
@samccone thanks!

**Comment by samccone** [comment]
@SomethingSexy would you like to open a PR bumping the version in package.json, component.json and bower.json ?

**Comment by SomethingSexy** [comment]
@samccone it looks like someone did already.

**Comment by samccone** [comment]
e1ffb18fa16bfad08b3607bd2d393e9bf600e2fb

:clap:

**Comment by SomethingSexy** [comment]
Thanks for doing that!

:+1:
