### ISSUE TITLE
Why package.json has different dependencies with bower.json?

### ISSUE THREAD

**Issue by drgrey87** [marionettejs/backbone.babysitter#70]
package.json:
`"dependencies": {
    "backbone": ">=0.9.9 <=1.3.2",
    "underscore": ">=1.4.0 <=1.8.3"
  },
`

bower.json:
`"dependencies": {
    "backbone": ">=0.9.9 <=1.2.3",
    "underscore": ">=1.4.0 <=1.8.3"
  },
`
P.S. The same problem in **backbone.wreqr** library, that's why i can't use **backbone v.1.3.2**

**Comment by samccone** [comment]
looks like we missed an update, @drgrey87 any interest in opening a PR?

**Comment by drgrey87** [comment]
@samccone ok

**Comment by drgrey87** [comment]
@samccone can you give me permissions?

**Comment by samccone** [comment]
you do not need permissions to open a PR, you can just fork it and open a PR that way :)

**Comment by paulfalgout** [comment]
@drgrey87 If you want, in this case, you can open a PR on github.com

Try this:
https://github.com/marionettejs/backbone.babysitter/edit/master/bower.json

**Comment by drgrey87** [comment]
Do you usually fix in master or create a new branch?

**Comment by paulfalgout** [comment]
`master` is fine here.  This mainly a stable repo.  `dev` is sooooo old.

**Comment by drgrey87** [comment]
ok, i got it ))

**Comment by paulfalgout** [comment]
Yep thanks!  Merged
