### ISSUE TITLE
Update peerDependencies

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.babysitter#75]
We should update the peerDependencies for babysitter for the Mn v3 release.  I think we can get away with possibly setting less restrictions on this library that maybe we would for Mn.

Possibly just:
```
"peerDependencies": {
    "backbone": "^1.3.3",
    "underscore": "^1.8.3"
  }
```
Since they're peer Deps anyone could still install older versions, but it would just complain on npm i.

**Comment by rafde** [comment]
I think this can be closed
