### ISSUE TITLE
Update tag to avoid mismatch errors

### ISSUE THREAD

**Issue by ChromeQ** [marionettejs/backbone.babysitter#77]
Looks as though v0.1.12 contains a bower.json that marks it as v0.1.11. This in itself is not too much of an issue as only results in:
`bower backbone.babysitter#*   mismatch Version declared in the json (0.1.11) is different than the resolved one (0.1.12)`

However, since v0.1.11 has a different version dependency of Backbone, it actually ends up using Backbone v1.2.3 (as defined in v0.1.11 bower.json) rather than the Backbone v1.3.3 (as defined in v0.1.12)
I hope that it is easy to update the tag and correct the version that bower downloads?

Thanks,,

**Comment by codynguyen** [comment]
I'm having the same issue which prevents updating to Backbone v1.3.x. It's been a while since @ChromeQ first reported this, is there any plan on an update?

Thanks!

**Comment by paulfalgout** [comment]
Getting this fixed
