### ISSUE TITLE
Deprecate backbone.babysitter

### ISSUE THREAD

**Issue by denar90** [marionettejs/backbone.babysitter#78]
We've integrated `babysitter` into Mn directly (thanks to @paulfalgout). Do we need to continue support this `babysitter` as separate lib?
@marionettejs/marionette-core any things?

**Comment by JSteunou** [comment]
Support... I do not know, maybe some people are using it. If issues are being opened and PR are clean, why not merge & release.

**Comment by denar90** [comment]
Agree. Closing it.
